### ISSUE TITLE
All links in a list download the same file

### ISSUE THREAD

**Issue by ram302** [elhardoum/recaptcha-protected-downloads#1]
Hi Samuel,

It's Rudy from StackOverflow. Firstly, thanks for this, I think this will help me with what I'm trying to accomplish. I downloaded your plugin and installed it. In testing, I added the following to a sample page, following the example in the plugin details window:

```
<br/><br/>

<a href="https://www.bing.com/[recaptcha-protected-download]https://github.com/bcit-ci/CodeIgniter/archive/3.1.3.zip[/recaptcha-protected-download]">BING CI</A>

<br/><br/>

<a href="https://www.google.com/[recaptcha-protected-download]https://www.apachefriends.org/xampp-files/7.1.1/xampp-win32-7.1.1-0-VC14-installer.exe[/recaptcha-protected-download]">GOOGLE XAMPP</A>

<br/><br/>

<a href="https://www.yahoo.com/[recaptcha-protected-download]https://www.wordpress.org/latest.zip[/recaptcha-protected-download]">YAHOO WORDPRESS</A>
```

But these links are all downloading the same `https://www.wordpress.org/latest.zip`. Also, I've changed the order of the links, and it looks like the first links in a list will download to whatever source is in the last link listed.

Also, I noticed when I click the "I'm not a robot" checkbox, the "(loading...)" text displays next to the last link in the list, as opposed to next to the link that was actually clicked.

**Comment by ram302** [comment]
I may have resolved this; it's a bit hack-ey, but it worked for me. I inserted the following code in line 64 of \wp-content\plugins\recaptcha-protected-downloads-master\assets\js\rcpdl.js: 

`hash = getHrefHash(this.hash);`

At this point, hash is somehow set to the hash of the last link listed; I'm not really sure why, yet. Let me know what you think.

**Comment by ownchoice** [comment]
Thanks! I am just starting out with Javascript, and I was struggling with this bug and you saved me!
